### PR TITLE
Upgraded packages and make hound only available in test mode

### PR DESCRIPTION
**Pull request by dkln**

### CODE REVIEW

**Comment by sn3p** [comment]
Hi @dkln, thanks for the PR!

**Comment by dkln** [comment]
I made a mistake that by doing this, the app (that uses test-selector) will probably not compile 🤦 I'll try to find a work around for this!

**Comment by sn3p** [comment]
> I made a mistake that by doing this, the app (that uses test-selector) will probably not compile 🤦 I'll try to find a work around for this!

@dkln can you elaborate what the problem is? In any case, we'll wait with creating a new release 😅

**Comment by sn3p** [comment]
@dkln are you able to find a fix? Otherwise we should maybe revert this change for now.
I didn't find the time to test it myself yet..

**Comment by dkln** [comment]
Sorry @sn3p not yet 😄 Yeah let's revert it and I'll take a look at it when I actually got the time 👍

**Comment by sn3p** [comment]
@dkln I'm not sure what the problem is, would you care to explain?

@fatboypunk did a similar PR (#32) before as well which I overlooked. Would this suffer the same problems regarding compiling in the app?

**Comment by fatboypunk** [comment]
https://github.com/DefactoSoftware/test_selector/pull/35 I think this works, hound was still used in some macro's which made it a dependency at compile, and therefore couldn't run. So i've removed all of the hound code. (I think it's not used anymore?)

**Pull request merged**
